#!/usr/bin/env bash
# -----------------------------------------------------
# Script   : red_hat_dominio 
# Descrição: Coloca uma máquina red hat no domínio 
# Versão   : 0.1
# Autor    : Luca Gorayeb <lucagorayeb@gmail.com>
# Data     : 21/01/2026
# Lincença : GNU/GPL v3.0
# -----------------------------------------------------
# Uso:
# -----------------------------------------------------

# Verifica se é root

teste=$(whoami)

if [[ "$teste" != "root" ]]; then
        echo "Precisa ser root"
	sudo su
fi

# Coloca o tombo da máquina 
read -p "Digite o FUJU da máquina (FJXXXXXX): " tombo

echo $tombo > /etc/hostname

# Instala o certificado de rede 

cp -r ./cert_TJRO-SSL-FWD.crt /etc/pki/ca-trust/source/anchors/

update-ca-trust extract

# Instala o lynx 

sudo dnf download lynx -y
sudo dnf install ./lynx* -y

# Autentica na rede
lynx pudim.com

#instala os pacotes desejados

pacotes="samba-common-tools realmd oddjob oddjob-mkhomedir sssd adcli krb5-workstation openssh-server"

dnf install -y $pacotes

# Caso tenha erro de dependencia
if [[ $? -ne 0 ]];then
        dnf --fix-broken install
        dnf install -y $pacotes
fi

# Realiza a descoberta do domínio

realm discover PVHDC2.PJRO.LOCAL

# Inserir no AD

read -p "Digite o seu cadastro: " cadastro

realm join PJRO.LOCAL -U $cadastro

getent passwd $cadastro@pjro.local

# Criar o arquivo sudoers do pjro 

while [ "$resposta" != "N" ]
do
	echo  "Digite o grupo que o usuário está presente no AD	para ter permissão de sudo:"
	echo  "Formato Aceito: %G_nome-do-grupo@PJRO.LOCAL ALL=(ALL:ALL) ALL" 
	echo ""
	read -p " > " grupo
	
	echo $grupo > /etc/sudoers.d/pjro
        echo ""
	read -p "Deseja adicionar mais um grupo? [S/N] " resposta
done

# Editar o arquivo sssd.conf

echo "[sssd]
domains = pjro.local
config_file_version = 2
services = nss, pam, ssh

[domain/pjro.local]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = PJRO.LOCAL
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u
ad_domain = pjro.local
use_fully_qualified_names = True
ldap_id_mapping = True
access_provider = simple" > /etc/sssd/sssd.conf

pam-auth-update --enable mkhomedir
session required pam_mkhomedir.so skel=/etc/skel/ umask=0022

# Instala o antivírus
tar -xf ./TrendMicro-Linux/TMServerAgent_Linux_auto_x86_64_Server_and_Workload_Protection.tar

./tmxbc install

